### ISSUE TITLE
Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by ddimitrioglo** [MitocGroup/deep-microservices-root-angular2#100]
After upgrading angular 2 => 4 the error `Cannot read property 'exclude' of undefined` had appeared.
For me worked changing typescript version to `"typescript": "2.0.10",`

**Comment by grigoreme** [comment]
Cannot update `package.json`, getting unknown codeclimate error.

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- The should be no errors related to angular updates during after executing "deepify server" from src project directory

<img width="1280" alt="screen shot 2017-06-08 at 15 28 07" src="https://user-images.githubusercontent.com/12330493/26928524-18f816b2-4c5f-11e7-97b5-0cb697bae08d.png">
