### ISSUE TITLE
Add tslint + Codeclimate dependencies and DOCS how to use on local (linux only for now)

### ISSUE THREAD

**Issue by grigoreme** [MitocGroup/deep-microservices-root-angular2#102]
I will add documentation for Mac OS later, need some Mac in hands to test it.

**Comment by avozicov** [comment]
Required docs are added in 109 branch. 
https://github.com/MitocGroup/deep-microservices-root-angular/blob/issue_109/docs/codeclimate.md

@grigoreme Please make a pull request to *dev* branch.

**Comment by avozicov** [comment]
**Test Passed**
Please refer to the link bellow
https://github.com/MitocGroup/deep-microservices-skeleton/blob/master/docs/codeclimate_cli.md

I have followed the steps from documentation on Mac OS Sierra and everything is working as expected
