### ISSUE TITLE
Implement a notification service to be used across all other microservices

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-microservices-root-angular2#60]

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- Info, Success, Warning, Error types of messages should be implemented and triggered on the expected events 
<img width="1280" alt="screen shot 2017-06-12 at 11 00 10" src="https://user-images.githubusercontent.com/12330493/27024315-c77a90b4-4f5e-11e7-96b6-0dd01e16e2f4.png">
<img width="1280" alt="screen shot 2017-06-12 at 11 00 38" src="https://user-images.githubusercontent.com/12330493/27024314-c77864c4-4f5e-11e7-8fe3-8269c32f5a9f.png">
